version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: seleznev808/foodgram2_backend
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    image: seleznev808/foodgram2_frontend
    volumes:
      - static:/app/result_build/build

  gateway:
    image: seleznev808/foodgram2_gateway
    volumes:
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/app/media
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8081:80
