version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: seleznev808/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    image: seleznev808/foodgram_frontend
    volumes:
      - static:/app/result_build/build

  gateway:
    image: nginx:1.19.3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8080:80
